### ISSUE TITLE
can't delete single photo from track

### ISSUE THREAD

**Issue by brusspi** [openstreetcam/openstreetcam.org#116]
I want to delete some pictures I recorded because the show only handlebars of my bicycle (Track file No. 166084).  But it does not work.

Regards,
Pieter

**Comment by allanmustard** [comment]
I have the same problem, the delete function does not work.  I tried both Chrome and IE, and neither browser seems to work.

**Comment by gappleto97** [comment]
Also doesn't work on Firefox. It's throwing:

```
TypeError: e.responseJSON is undefined[Learn More]  main-min.js:557:1253248
	success https://www.openstreetcam.org/js/main-min.js:557:1253248
	a https://www.openstreetcam.org/js/main-min.js:557:48238
	fireWith https://www.openstreetcam.org/js/main-min.js:557:49013
	T https://www.openstreetcam.org/js/main-min.js:557:92518
	n https://www.openstreetcam.org/js/main-min.js:557:98770
```

**Comment by gappleto97** [comment]
I'm going to guess this is the block causing the issue here:

```javascript
$.ajax({
type: 'POST',
url: '/1.0/photo/remove/',
data: {
photoId: i.id
},
success: function (e) {
e.responseJSON.status.apiCode != 671 && location.reload()
},
error: function (e) {
e.responseJSON.status.apiCode != 671 && location.reload()
}
})
```

It looks like somebody just copy/pasted wrong there. On the other hand, it appears to have actually deleted on the server end, so that works out.

**Comment by PeteDevoy** [comment]
> It looks like somebody just copy/pasted wrong there. On the other hand, it appears to have actually deleted on the server end, so that works out.

Yes, this appears correct:

![http requests](https://user-images.githubusercontent.com/4375326/26889839-59f9286c-4ba7-11e7-99af-fbb5b42eecdf.png)
(clicked delete twice)

The undefined error (#issuecomment-304554742) is because, on success, ´e´ is the object which contains ´status´ not ´e.responseJSON´:

![image](https://user-images.githubusercontent.com/4375326/26890675-46d14b04-4baa-11e7-8131-ea7f597a4cf5.png)

I was going to issue a pull request but it seems like this repo is out of date:
https://github.com/openstreetcam/openstreetview.org/blob/7f9da68eafa1adbcc49ce46827328baf5a1a4166/js/views/DetailsPaneV.js#L115

Maybe someone knows why? @martijnv-telenav

**Comment by james2432** [comment]
@PeteDevoy because they maintain 2 git repos... one internal with all their proprietary stuff and this one that I really have no idea at this point why it's even here....

**Comment by PeteDevoy** [comment]
@james2432 Have TeleNav made a statement to that effect?  Because they said they want it to be "[100% open](https://youtu.be/XuGjahx8CFc?t=1220)" so perhaps it is just bad governance.

[https://youtu.be/XuGjahx8CFc?t=1220](![YouTube openess](https://user-images.githubusercontent.com/4375326/26891356-a1bf3ea2-4bac-11e7-9d4a-31957a92662d.png))

**Comment by james2432** [comment]
@PeteDevoy not officially anywhere, but have done so in bug reports here on github:
https://github.com/openstreetcam/android/issues/8#issuecomment-249115600
https://github.com/openstreetcam/android/issues/8#issuecomment-288745683

**Comment by PeteDevoy** [comment]
Ehhhhhhh, hopefully someone from TeleNav can give some detailed info because if this is indicative of the way the whole project is going I would be more interested in talking with the OSM community about ways in which a project of this nature could be done in a less centralised fashion than getting further involved in this one.

**Comment by PeteDevoy** [comment]
@james2432 @rugk @grinapo
If anyone is interested I started a thread on the forum would be curious to hear your thoughts... https://forum.openstreetmap.org/viewtopic.php?pid=650007

**Comment by bogdans-telenav** [comment]
Sorry for the late response. Since your report the delete api was fixed. If you still encounter any other issue please report it and we will reply as soon as possible.
