### ISSUE TITLE
Documentation for the API

### ISSUE THREAD

**Issue by Xevib** [openstreetcam/openstreetcam.org#30]
Please, documentate the API to play with it :smile:

**Comment by alexandrui-telenav** [comment]
😄 will happen

**Comment by ToeBee** [comment]
Ping on this? I just ran into a problem (my own fault) that I could script my way out of with a few API calls...

**Comment by ToeBee** [comment]
Actually, it turns out it wasn't my own fault. The double upload bug has made a right mess of all of my recent traces. I need to be able to script deleting the duplicate images. Or I will need to delete and re-upload them all.

**Comment by bogdan-telenav** [comment]
But now with your fix this is not a problem anymore that the script duplicate the images

**Comment by ToeBee** [comment]
Yes and I have deleted and re-uploaded most of the affected tracks. There is one that I am having trouble tracking down the original pictures for because I'm not sure when they were taken (since the website only shows uploaded date - #44). However a usable API would have saved me time and gigabytes.

**Comment by mvexel** [comment]
Bump this -- someone on Twitter was asking about it too.. https://twitter.com/juancarlospaco/status/1034940780606050304

**Comment by mvexel** [comment]
http://api.openstreetcam.org/api/doc.html

**Comment by bogdans-telenav** [comment]
Closing this since we now display an api documentation.
