### ISSUE TITLE
Cooperate with Mapillary? / Difference to Mapillary?

### ISSUE THREAD

**Issue by rugk** [openstreetcam/openstreetcam.org#60]
https://www.mapillary.com/ basically does the same job as this new project. The images are under different CC licenses, so you should be able to use them and incooperate them into your own project.

They also provide more advantaged libraries such as [mapillary.js](https://github.com/mapillary/mapillary-js), which renders and shows pictures in a nicer way than the current openstreetview.org website does.

Additionally they want to publish their clients under open-source licenses (https://github.com/mapillary/mapillary_issues/issues/1791).

So I don't really know what is the sense of this project. Mapillary already does it and does it better (from a feature and UX perspective). So why should I, as a user of Mapillary, switch?
Or - which would be better - could you just cooperate to integrate the images you collect into both databases?

**Comment by james2432** [comment]
Heh. The major difference is that you remain the owner of your photos that you upload in OSV. This is also not a for profit company like Mapillary that gains $ off work of others(people using the app). You cannot host your own version of mapillary's site(closed source) in the case of sensitive data(It would be like comparing Linux to MS Windows, yes they do essentially the same thing (allow you to use the computer) but differ much in the philosophy of openness). 

Mapillary has no advantage cooperating with OSV as it does not make a profit(which Mapillary is). Mapillary copyrighting photos that the users take is the major issue where as with OSV, you remain the owner of your photos and can delete them at anytime. OSV is also purely to improve OSM, which is great. Mapillary is in it to sell a service off the backs of other people while saying you may use it to improve OSM.

**Comment by rugk** [comment]
> The major difference is that you remain the owner of your photos that you upload in OSV.

You altos do with Mapillary. You license your photos under a CC license, so of course Mapillary can use it.

> You cannot host your own version of mapillary's site(closed source)

That's a good argument.

> It would be like comparing Linux to MS Windows [...]  but differ much in the philosophy of openness

This comparison is invalid. The thing is that Mapillary is quite open. Have a look at GitHub and you see that they develop much things and share the code under a free license.

> Mapillary copyrighting photos that the users take is the major issue

Could you provide sources for this statement. At Mapillary you - as a user - own the copyright and just publish the pictures under a CC license, which of course allows Mapillary to use it.

> Mapillary has no advantage cooperating with OSV

Maybe, but OSV would clearly have...

**Comment by james2432** [comment]
https://www.mapillary.com/terms
1.2      Commercial Use. You may not use the Mapillary Solution for any Commercial Use except as separately agreed between us in a signed writing. Other than for your Non-Commercial Use, or as otherwise permitted by the Outbound Terms, you may not use, sublicense, transfer, distribute, make derivative works of, or make available, the Service or Content. Such activity is not licensed or authorized under these Terms and if undertaken may result in pursuit of all available remedies for intellectual property rights (including copyright infringement), the availability of which you hereby acknowledge.

CC-BY-SA allows commercial use.

The comparison is very valid(between Linux and Windows) Linux you have access to the code(kernel, drivers,etc) where as Windows you do not. OSV you have access to the website source and everything else, mapillary, you do not.

**Comment by rugk** [comment]
To be fair I think I should ping @mapillary @sandrauddback

**Comment by PaulColinSimpson** [comment]
I think someone from OSM should contact Mapillary. I did a lot of work for Mapillary specifically for the OSM project and I believe these tracks should be imported into OSV.

**Comment by pbb72** [comment]
> This is also not a for profit company like Mapillary

OpenStreetView is not a company. OSV is (quoted from http://openstreetview.org/terms/) "an application developed by Telenav, Inc." Telenav is a for profit company that "gains $ off work of others(people using the app)".

> you remain the owner of your photos that you upload in OSV

Here again the OSV terms seem to indicate something else:

> You hereby grant to Telenav a worldwide, royalty-free, non-exclusive, perpetual, irrevocable license to do any act that is restricted by copyright, database right or any related right over anything within the Content, whether in the original medium or any other.  These rights explicitly include commercial use, and do not exclude any field of endeavor.  These rights include, without limitation, the right to sub-license the Content through multiple tiers of sub-licensees and to sue for any copyright violation directly connected with Telenav's rights under these Terms of Use.
> 
> You agree that Telenav may at any time filter, alter, modify, redact, crop or delete your Content in whole or in part in its discretion, including in order to render the Content suitable for use onOpenStreetView.  To the extent allowable under applicable local laws and copyright conventions, you also waive and/or agree not to assert against Telenav or its licensees any moral rights or other rights that you may have in your Content that would otherwise preclude Telenav from filtering, altering, deleting, or using, copying or distributing your Content.  You acknowledge and agree that we may continue to store, display and otherwise exercise the rights with respect to your Content after termination, deactivation, or archiving of your account.

What is the value of being the "owner" when you grant Telenav the right to do as they wish with your photos?

> OSV [...] does not make a profit

Is it stated anywhere that this is and will be the case? Telenav is a publicly traded company, and I doubt strongly they will not want to get a return on their investment in OSV.

I am far from an expert on licensing and commercial use, but to my untrained eye it seems that this is not at all openness and freedom. The comparison to Linux seems very far-fetched.

But maybe I am misunderstanding? I will gladly be proven wrong!

Please note: I am NOT comparing OSV to Mapillary here. Maybe OSV is better than Mapillary, but it seems to me that it is not as liberal as it is presented here.

**Comment by james2432** [comment]
You do remain the owner of your photos, but you also give free access to Telenav to do what they want with it (which mapillary has btw). Essentially just legal jargon to not get sued if you decide you don't want them to use your photo for xyz reason(Example: photo blurring license plates, auto cropping out dashboards), but you can download your photos and delete your photos/tracks if you decide you no longer want to participate in OSV.

Telenav is a company that produces in car navigation systems, I am aware of this, and they have struck a deal with Toyota for their in car nav systems. Personally a car system using OSM data is a major stride forward from the giants like TeleAtlas(TomTom), Navteq(Garmin) and Google. If I offer data that will improve in car navigation, why the hell not?

**Comment by rugk** [comment]
Oh, actually this is very interesting. So the different of OSV to Mapillary seems to tinier than previously thought.
So who's Linux and Windows here? Maybe Mac OS is needed in this metaphor.*

\* I do not suggest to use this metaphor (again). Such comparisons are just silly.

**Comment by rugk** [comment]
BTW as for [the terms @james2432 quoted here](https://github.com/openstreetview/openstreetview.org/issues/60#issuecomment-241529172):
> 1.2 Commercial Use. You may not use the Mapillary Solution for any Commercial Use except [...]

These refer to the "Mapillarly Solution", which - IMHO, just applies if you e.g. want to use their website or website APIs (if there are some) to e.g. bulk-download photos. This is how they make money and they [clearly state it here](https://www.mapillary.com/solutions).
This - however - does not mean that the photos you upload would not be your own ones anymore. As said the photos are CC licensed and the name of the author is stated.

----
@james2432 No need to dislike. Convince me that the difference is bigger...

**Comment by pbb72** [comment]
I really don't see that thing with being the owner of your photos in OSV, and where that would not be the case in Mapillary.

Actually, I've skimming the terms further, and I don't find any rules that says that I can't just take your photos from OSV, and use them for my own personal gain, and even state that they are my own photos.

In contrast, on Mapillary all photos have a BY-SA 4.0 license, which means I am obliged to credit the owner, and I can not use it under different licenses.

I don't have any problem with the provider (either OSV or Mapillary) being a commercial company and making a profit on my contributions. But this needs to be clear and in the open.

**Comment by rugk** [comment]
> I don't have any problem with the provider (either OSV or Mapillary) being a commercial company and making a profit on my contributions. But this needs to be clear and in the open.

Yeah, that's exactly what matters here.

What also matters on my opinion: You two (companies) seem to share the same goal and bo0th want to be open companies, want to make an open version of StreetView and so on. So please just share the images with each other!
Only collaboration helps to reach this goal, competition does not help here. That's the reason why I've stressed this so much already in my initial post.
And it is possible: Mapillary [states](https://www.mapillary.com/manifesto) that their service will always be free for non-commercial and [OpenStreetMap](https://www.mapillary.com/osm).

BTW: Has anyone reached out to Mapillary yet?

**Comment by ToeBee** [comment]
> Actually, I've skimming the terms further, and I don't find any rules that says that I can't just take your photos from OSV, and use them for my own personal gain, and even state that they are my own photos.

Well there is this in the OSV terms: 
> ... and by licensing its imagery under Creative Commons Attribution-ShareAlike 4.0 International ("CC-By-SA License") ...

**Comment by pbb72** [comment]
@rugk Mapillary is aware :smile: 
https://twitter.com/peterneubauer/status/768028539421679616

**Comment by Seudodata** [comment]
Talking about the photos being property of the contributors, I'm looking for a way to upload pics taken with Mapillary's app to OSV and viceversa. Does anybody know how to do this?

**Comment by bogdan-telenav** [comment]
@Seudodata you can use upload scripts with Python https://github.com/openstreetview/upload-scripts/tree/master/upload_photos_by_exif

**Comment by pbb72** [comment]
Here are the Python scripts for use with Mapillary: https://github.com/mapillary/mapillary_tools/tree/master/python

**Comment by Seudodata** [comment]
Thanks for your answers @bogdan_telenav and @pbb72. I was looking for a more traight forward solution for non tech users.

**Comment by mvexel** [comment]
@Seudodata There is an upload desktop app as well, one that was developed by an OSV user ( @james2432 do you have the link handy? ) as well as one developed by us. These allow drag and drop.

@pbb72 The Mapillary and OSV offerings are very similar in some ways. Very different in others. Mapillary runs a business specifically around the imagery itself, which they need to market to customers. OSV collects the imagery solely to improve OSM. I see that as a fundamental difference. Of course Telenav (I am also working for them btw) has something to be gained from this but it is much more indirect. Our business is car navigation and we use OSM data to power that product in some cases. So the better OSM is, the better and more attractive our product is :) That said, we're happy to collaborate.

On a technical level, Mapillary is more mature right now, but we have some things going on under the hood that will benefit OSM much more. One example is map matching - every OSV trip and image is matched to an OSM way, so for example when we work for example on iD integration for OSV we can link all images to an OSM way easily, to avoid a very messy display like here: 

<img width="536" alt="screen shot 2016-11-10 at 9 03 07 am" src="https://cloud.githubusercontent.com/assets/120452/20184122/d85e629e-a724-11e6-9d75-a9853f0f3ce3.png">

You will see more of these types of features optimized for OSM appear in OSV on a regular basis.

If anyone wants help transferring their existing photos into OSV, let me or anyone from the team here know and we can help with that.

**Comment by james2432** [comment]
@martijnv-telenav I do: https://github.com/osmottawa/OSVUploadr/releases  Although it's not polished, it works the same as the python upload scripts(using the same backend API)

**Comment by jesolem** [comment]
Hello everyone, I just got this thread forwarded today. Let me give some input from Mapillary's side. I'd like to answer specific points/questions but keep it short as I don't want to hijack an issue here with Mapillay propaganda. Fair?

@rugk Thanks for bringing this up and for explaining Mapillary.

@james2432 The for-profit part I think has been answered but just to make it clear OSV is a service from Telenav Inc, Mapillary is a service from Mapillary AB. Both companies are for profit organizations by nature. As @mvexel points out, with different business models and at different ends of the value chain (In this case Mapillary feeds data to OSM, Telenav builds services on top of OSM).

@PaulColinSimpson We have been available in OSM editors for a very long time and Mapillary data is free and available for OSM use. We're in iD, JOSM plugin, and other third party integrations like MapBox navigation tool. See for example:
http://blog.mapillary.com/update/2016/06/26/tools-edit-OSM.html
http://www.mapillary.com/osm

@mvexel About map matching, we do that too and the data is available for download under ODbL. Announced before SotM, for example [here](http://blog.mapillary.com/update/2016/09/22/state-of-the-photo-map-2016.html) . We're going to expose two sets of tiles and data with and without map matching soon. 


### Differences:
- The main difference is that Mapillary is a platform for street imagery and data available to everyone, Telenav focuses OSV for OSM only. Being available on other platforms and for other use cases than OSM is a great multiplier and in the end gives more data for everyone. Quoting myself from the [blog post above](http://blog.mapillary.com/update/2016/09/22/state-of-the-photo-map-2016.html):
```For example, to date more than three-quarters of data contributed to Mapillary comes from sources completely unrelated to OpenStreetMap. Bringing in all of these diverse sources and making the photos and data fully available for OpenStreetMap in JOSM and the iD Editor, in navigation tools, etc. is one clear way how an inclusive approach has positive effects for OpenStreetMap.```  
- Open APIs. Mapillary has over 300 integrations today, ranging from people scripting and hacking against our platform to real professional integrations. My personal favorite is this one http://mapbox.github.io/osm-navigation-map/
- Mapillary's product is services to provide images and data, Telenav's product is car navigation systems.

### Openness:
- As pointed out above, the terms and image licenses are the same. Rights granted to the company to distribute and build on the images, CC BY-SA outgoing license.
- When it comes to open source we each open source different parts of the system. For Mapillary we share our computer vision pipeline, viewer, and a bunch of tools. Telenav open sources apps and the website.
- A key part of being open is that people can use and build on top of the platform using APIs. Mapillary has full APIs for everything with clear terms on how to use them. 

Finally, regarding collaboration: We have met the OSV team several times to talk collaboration. Last time I flew to the Bay Area and visited the Telenav office and we had a long conversation in September. Nothing conclusive or concrete to report yet, unfortunately. 

OK, this became longer than I planned. Hope this can help everyone in their thinking about this.

**Comment by abienvenu** [comment]
The huge difference to me is the copyright :

- © Telenav and OpenStreetView Contributors
- © Mapillary

As @james2432 said, OSV contributors own the uploaded photos, and the license cannot be modified unless all owners (contributors) give their agreement to the change. Mapillary can change the license of the photos at any time for anything they like without asking permission from anyone.

I wish Mapillary will soon change the copyright to "© Mapillary and Mapillary contributors", because I find it crucial that we, as a community, own the work we produce.

**Comment by peterneubauer** [comment]
Reading on http://openstreetview.org/terms/ :

@abienvenu that is not the copyright for the content - it is the requirement for the credits if you use the data under the CC-By-SA license of the outgoing content: `We require that you use the credit “© Telenav and OpenStreetView Contributors"`


However, you don't have a right to any agreements to change etc. All rights are granted to  Telenav alone for the content that you upload to this project. 

`You hereby grant to Telenav a worldwide, royalty-free, non-exclusive, perpetual, irrevocable license to do any act that is restricted by copyright, database right or any related right over anything within the Content, whether in the original medium or any other.  These rights explicitly include commercial use, and do not exclude any field of endeavor.  These rights include, without limitation, the right to sub-license the Content through multiple tiers of sub-licensees and to sue for any copyright violation directly connected with Telenav's rights under these Terms of Use.`

AINAL but this looks pretty Telenav-only-copyright-granted-by-the-contributor to me?

**Comment by abienvenu** [comment]
@peterneubauer the outgoing content is the point. If I download the OSV data, it is “© Telenav and OpenStreetView Contributors", so Telenav alone cannot revoke its CC-By-SA license, and I am sure I can use this data under CC-By-SA forever.
Let's make a nightmare : Google buys both Telenav and Mapillary, and changes the license to "© Google all rights reserved". Fortunately, some guy has secured an external copy of the data, and makes it available to all under CC-By-SA. My understanding is that Google can prevent him from publishing the Mapillary data, because it is © Mapillary, and Mapillary revoked CC-By-SA. But Google will not be able to lock down the OSV data, unless all OSV contributors shoot themselves in the foot and agree to change the existing license on the OSV data.

**Comment by rugk** [comment]
> Telenav alone cannot revoke its CC-By-SA license

CC licenses [are not revokable](https://creativecommons.org/faq/#what-if-i-change-my-mind-about-using-a-cc-license) at all, so if you have a copy of the data you can *always* distribute (and modify etc.) it according to the CC license.
The only thing, which they can do is relicensing all photos and publishing them under a new license. Afterwards all these photos may be properitary or whatever...
But if you have a copy, you have a copy. CC licenses cannot be revoked as copyright holders cannot "change the past" - this is made sure in the CC licenses (and also all FLOSS licenses BTW).

> My understanding is that Google can prevent him from publishing the Mapillary data, because it is © Mapillary, and Mapillary revoked CC-By-SA.

And exactly this is the wrong understanding as I explained above.


>  But Google will not be able to lock down the OSV data, unless all OSV contributors shoot themselves in the foot and agree to change the existing license on the OSV data.

As @peterneubauer has showed by quoting the terms and conditions from Telenav (OSV) both Mapillary and Telenav can do this, so no, Google could do the same with OSV data.

----

So all in all I see no "street view"-like provider, which does not reserve a right to change the license later.

**Comment by jesolem** [comment]
@abienvenu Thanks for your input. You are misunderstanding several points. Let me explain. 

#### Regarding ownership:   
*Mapillary never ever takes ownership or copyright of photos submitted!*

From the opening paragraph in our terms:
```
We would like to assure the community that nothing in these Terms requires transfer of your ownership of photos taken...
```

#### Regarding copyright and credits:  
In the website footer we display `Copyright © Mapillary`. This is the website copy and design, not the content served. Read the terms and you will see that we clearly never take ownership or copyright, we get a license to use the contributed content, that's it. 

As for credits, we recommend the following wording:
`Photos from Mapillary, CC BY-SA, by @username.`

#### Regarding revoking CC license:
@rugk is right, CC licenses are not revokable. I think this is your conclusion based on a misunderstanding of the footer copyright notice (above).

**Comment by abienvenu** [comment]
Good points @rugk and @jesolem. Legal stuff is hard to interpret, so may I submit another practical question : is one allowed to upload his Mapillary sequence to OSV : 
- if she kept an original copy of the sequence on his hard drive ?
- if he did not keep any original copy, but downloads it back from Mapillary through the API ?

What about the other way (upload OSV sequence to Mapillary) ?
One point is that when we download back photos from Mapillary, we have a "Mapillary" watermark on the lower left and a "M" watermark on the upper right of the photo. These make me feel like we do not own our photos any more. OSV are not watermarked for now.

**Comment by rugk** [comment]
Yes all things you mentioned should work as you stay the author of them.
I have never noticed any watermark in Mapillary. Of there is one that's of course not so nice.

**Comment by jesolem** [comment]
@abienvenu - short answer: yes.

> if she kept an original copy of the sequence on his hard drive ?

Yes. This is the simplest way. You retain full ownership and when you submit a copy to Mapillary you grant a license for Mapillary to use but no transfer of ownership.

> if he did not keep any original copy, but downloads it back from Mapillary through the API ?

Yes, this will work too. You can download the original file if you are the contributor. This is the exact file with EXIF and all, just as it was submitted and contains no watermark. You can download this from the viewer through the menu on the right-hand side if you are authenticated as the contributing username. 

The first option is the best, by far. Even better would be not having to upload to two services, but I think we can all agree on that.

**Comment by pbb72** [comment]
Let me take it even a step further:

* Is it allowed to download someone else's photos from Mapillary, and upload them to OSV, if I can include the proper credentials of the owner?
* Is it allowed to download someone else's photos from OSV, and upload them to Mapillary, if I can include the proper credentials of the owner?

**Comment by stephan75** [comment]
@rugk ... But yes I remember some mapillary images used in the OSM diaries that have a watermark in one corner.

**Comment by jesolem** [comment]
@pbb72 Hey! Quick answers to your questions from the Mapillary side.

> Is it allowed to download someone else's photos from Mapillary, and upload them to OSV, if I can include the proper credentials of the owner?

Anyone can download a photo from Mapillary and do what they like as long as they respect the CC BY-SA license. If it is allowed to upload that to OSV is a question for Telenav.

> Is it allowed to download someone else's photos from OSV, and upload them to Mapillary, if I can include the proper credentials of the owner?

No. Mapillary needs all contributions to be under the Mapillary Terms. 

On a few unique occasions we have accepted CC BY content by a contributor but then always with the source and license in the profile description, with the contributor's agreement that this is acceptable attribution, and we carefully keep track of these. Keeping track of multiple licenses and thousands of attribution requirements is not something our small team can or wants to do.

**Comment by pbb72** [comment]
@jesolem That is a major bummer, and one that I feel Mapillary should be more open about. Why provide CC-BY content, but not accept it?

**Comment by pbb72** [comment]
@rugk, @stephan75 All Mapillary photos are watermarked, if you download them through the viewer. Only if it is your own photo, is it possible to download the original, non-processed photos (via the photo details dialog).

**Comment by jesolem** [comment]
@pbb72 Sure, it is Section 1 of the Terms though. We could work something into the FAQ/Help as we're revamping it.

We don't want to be responsible for tracking every possible attribution requirement. It would destroy us.

**Comment by pbb72** [comment]
@jesolem Since this is getting off-topic, I opened a forum post on the subject at https://forum.mapillary.com/t/opening-up-for-3rd-party-cc-by-content/739

**Comment by jesolem** [comment]
@pbb72 I had the same feeling ;) 
Thanks.

**Comment by drkludge** [comment]
> ...
> They also provide more advantaged libraries such as mapillary.js, which renders and shows pictures in a nicer way than the current openstreetview.org website does.
> ...
> So I don't really know what is the sense of this project. Mapillary already does it and does it better (from a feature and UX perspective).

@rugk In my opinion the Mapillary site took a step backwards when they redesigned their website. The site used to rock because the site would show a reduced image in a SVG image.  That made for a great way to scroll through a set of images to find the feature that I wanted to add to OSM.  The site was always a marketing piece but now it is slow clunky marketing piece.  OSV works much better for locating images for things that I want to add to OSM.  I could careless if it is pretty.  I am a heavy contributor to both projects by the way so I am not picking favorites here.

> So why should I, as a user of Mapillary, switch?

You do not have to switch as I note below.

> Or - which would be better - could you just cooperate to integrate the images you collect into both databases?

On the one hand, the format of the images on the phone are different for each system.  On the the other hand, it is up to me to determine who I allow to have my images.

@Seudodata 
> Talking about the photos being property of the contributors, I'm looking for a way to upload pics taken with Mapillary's app to OSV and viceversa. Does anybody know how to do this?
...
> I was looking for a more straight forward solution for non tech users.

I do not think you will have much joy here as far as a "straight forward solution".

1.One of the methods that I have used to add features to OSM is by taking pictures.  The plus for both systems is that they manage photos for me.  As I mentioned before the systems are incompatible. I think it is a mistake to say that the systems are anywhere like a street view.  If you are looking for straight on image of the road from a bike or car, then their system will work for you. The main short coming is that neither system has a convenient way of generating a peripheral view. I have experimented with a [side view](https://www.mapillary.com/app/user/drkludge?lat=33.512314882868736&lng=-112.09994965644727&z=20&pKey=nqjSW4Lav5q9aBAp7fRhWA&focus=photo&menu=false) for several photos.  It is hard to hold your phone at the side of a car when the window is curved.  I looked at what MapBox was doing with their experimental method of collecting images but it fails on the convenience and affordable side of the house. 
2.I use the Mapillary phone app.
3.I configured the application to log to an SD card.  If your phone does not have a SD card, then you will have to have a phone with lots of memory.  I also had to use an SD card because my long photo runs would fill up my phone.
4.After I have finished taking images, then I perform minimal edits in the review phase.  I just don't have the time to do all that Mapillary would like me to do.
5.I exit the phone app.
6.I switch to the file manager on the phone. I have a backup directory on my SD card.  I copy all my Mapillary image directories to the backup directory.
7.Now that my images are backed up, I use the Mapillary phone app to upload the images to their site.
8.At home I move backup photos from my SD card to my computer.
9.I then use the OSV upload script to contribute the same photos to OSV.
10.The OSV Python3 scripts were really challenging to use.  I know that we are all moving to Python3 but that added a level of difficulty to the process.  I submitted around six issues to @james2432's Java loader script.  The major enhancement is that the script now allows you to pick multiple directories of images to upload.   The script is now more convenient to use than the JOSM Mapillary uploader. @Seudodata I would try @james2432's script with the procedure above. Another set of eyes from another user would help.  Some of the issues that I submitted were geared toward making the script more straight forward based on your question here.

I make these observations:
-  The [TIGER](http://wiki.openstreetmap.org/wiki/TIGER) import was a wonderful thing.  TIGER provided a useful map.  Mapillary/OSV help build on that foundation by making it easier to make the map better.
- I snort laugh when other mappers tell me that I have to run out and GPS everything before I add something to the database.  That is just not practical in the US.  I've be working hard to use that method but I have not made much of a dent.
- This idea that [Armchair mapping](http://wiki.openstreetmap.org/wiki/Armchair_mapping) is a bad thing is just more fear mongering.  It is more of Europe telling the US how to do things without really trying to think through how to map the US with a lower density of mappers per square mile.  Neither GPS nor imagery are completely accurate.  On top of that I've made mistakes and corrected the mistakes with both methods of mapping: survey and armchair.  I've improved the map with both.
- The advantage of contributing to Mapillary/OSV is that you get to be [Tom Sawyer](https://www.youtube.com/watch?v=8xZm2UOam74) except for collecting valuable trinkets. Other mappers have used my images to improve the area that I map.  Just like me they have made mistakes and yet we have recovered and improved the map.  The advantage of local knowledge is not as relevant as it used to be.  There is now a virulent faction in the OSM community that has done more damage to community than any alleged import has done.

**Comment by grinapo** [comment]
Out of sheer necrophilia let me react on this ancient issue as well.

First, the "you grant the long-list-of rights to Company" results that the company can re-license your images whatever they please. It does not interfere with your rights to license your images however you please, and the same image will be licensed under some separate, distinct terms, and one can choose whichever he wants to (as in dual licensing cases). This basically grants the companies to use the images in cases where the CC license would reject it.

Then... I wasn't aware the OSC existence, so I have looked around. As for comparing to Mapillary, this service seems to be invery early stages of usability. I see no API, no useful tools (like DOWNloading the images); there's a JOSM plugin which kind of works, but leaves much to desire (which is basically true to mapillary plugin to some extents as well). The licenses are similar. So I'd say I wouldn't use OSC due to the lack of usability compared to Mapillary, but I see no reason why it couldn't be similarly useful in a few years.

The most interesting point raised here was the exchange between the two projects. From the approach of both it would seem obvious that both would benefit from sharing/exchanging their imagery, possibly by simply licensing the imagery (due to their acquired power of relicensing) to the other company. Based on thge real world events, however, it seems that the real intents slightly differ from the PR material, and it seems Telenav doesn't quite feel compfortable to share their collection of our imagery and metadata with Mapillary (while Mapillary seems to be rather open about it, but that's a bit anecdotal evidence). 

I really want to suggest to both Telenav and Mapillary to collect and consider pros and cons of cross-licensing and exchanging all the imagery and metadata, and possibly be open about it, since we - as a community - lose a lot by the fragmentation of efforts. I would gladly submit all my data to both except I don't feel like running two apps at once, and even less for manually duplicating my imagery to satisfy the disjunct desires of both companies. As an OSM editor I want to use one source (and I don't care which company is it, my decision involves criterias about usability, speed and precision) and I would hate to use two, three or more. If they both promised to use open licenses, they both want to use the imagery in their own commercial endeavour, then they may share our data and try to do their business separately. Maybe the worse one will disappear after some time, possibly neither of them since they will accumulate a different volunteer and user base. And they both can earn more money by using lots more data than alone. 

Mapillary has been open to implement some advanced tech to help OSM editors (and themselves, why not?), and have rejected plenty of ideas du to whatever reason, which is normal. I guess OSC would implement some other advanced tech, possibly some of mapillary rejects. I see plenty of opportunities for both companies, which could use the same imagery database.

Oh, and another one, pretty important. Neither companies allow bulk imagery/metadata mirroring, as far as I know. Both companies' ToS contain that they have the right to cease any or all services anytime with any reason or no reason at all. I would really feel more safe to know that I am allowed to mirror the data in case of the company throwing in the towel. 

Sorry for the Wall of Text. :-)

**Comment by grinapo** [comment]
(Seen an interesting tidbit on a different issue thread: "We cannot upload that [some code in question] to github since it's not **obfuscated** anymore." Let's use the phrase "open source" with care.)

**Comment by martijnv-telenav** [comment]
This issue has now been discussed at length and I think there's been valuable input from the street level imagery community as well as from @jesolem from Mapillary (Thanks!) I will close because there's been no more input for well over a year. Feel free to reach out at hello@openstreetcam.org at any time if you have questions or concerns.
